development:
  adapter: postgresql
  encoding: unicode
  database: SquashSimulator_development
  pool: 5
  host: localhost
  username: benjaminclayman
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: SquashSimulator_production
  pool: 5
  username: benjaminclayman
  password:
