User.delete_all
Team.delete_all

u1 = User.create(:email => 'benjamin_clayman@alumni.brown.edu', :password => 'a', :password_confirmation => 'a', :team => 'Brown')
u2 = User.create(:email => 'sam.clayman@alumni.yale.edu', :password => 'a', :password_confirmation => 'a', :team => 'Yale')
u3 = User.create(:email => 'jay.dolan@middlebury.edu', :password => 'a', :password_confirmation => 'a', :team => 'Middlebury')
u4 = User.create(:email => 'will.katz@bates.edu', :password => 'a', :password_confirmation => 'a', :team => 'Bates')
u5 = User.create(:email => 'todd.harrity@princeton.edu', :password => 'a', :password_confirmation => 'a', :team => 'Princeton')
u6 = User.create(:email => 'george.miller@williams.edu', :password => 'a', :password_confirmation => 'a', :team => 'Williams')
u7 = User.create(:email => 'albert.shoihet@uwo.edu', :password => 'a', :password_confirmation => 'a', :team => 'Western Ontario')
u8 = User.create(:email => 'will.hartigan@cornell.edu', :password => 'a', :password_confirmation => 'a', :team => 'Cornell')

Trinity = Team.create(:name => 'Trinity', :team_id => 7689, :ranking => 1)
Harvard = Team.create(:name => 'Harvard', :team_id => 7679, :ranking => 2)
Princeton = Team.create(:name => 'Princeton', :team_id => 7676, :ranking => 3)
Yale = Team.create(:name => 'Yale', :team_id => 7680, :ranking => 4)
Rochester = Team.create(:name => 'Rochester', :team_id => 7681, :ranking => 4)
SLU = Team.create(:name => 'SLU', :team_id => 7717, :ranking => 5)
FM = Team.create(:name => 'F&M', :team_id => 7713, :ranking => 6)
Cornell = Team.create(:name => 'Cornell', :team_id => 7683, :ranking => 7)
UWO = Team.create(:name => 'UWO', :team_id => 7684, :ranking => 8)
Williams = Team.create(:name => 'Williams', :team_id => 7700, :ranking => 9)
Dartmouth = Team.create(:name => 'Dartmouth', :team_id => 7685, :ranking => 10)
Columbia = Team.create(:name => 'Columbia', :team_id => 7691, :ranking => 11)
Bates = Team.create(:name => 'Bates', :team_id => 7687, :ranking => 12)
Penn = Team.create(:name => 'Penn', :team_id => 7682, :ranking => 13)
Navy = Team.create(:name => 'Navy', :team_id => 7694, :ranking => 14)
Brown = Team.create(:name => 'Brown', :team_id => 7693, :ranking => 15)
Middlebury = Team.create(:name => 'Middlebury', :team_id => 7678, :ranking => 16)
Wesleyan = Team.create(:name => 'Wesleyan', :team_id => 7702, :ranking => 17)
GWU = Team.create(:name => 'GWU', :team_id => 7718, :ranking => 18)
Bowdoin = Team.create(:name => 'Bowdoin', :team_id => 7686, :ranking => 19)
Amherst = Team.create(:name => 'Amherst', :team_id => 7690, :ranking => 20)
Drexel = Team.create(:name => 'Drexel', :team_id => 7703, :ranking => 21)
Conn = Team.create(:name => 'Conn', :team_id => 7698, :ranking => 22)
Hamilton = Team.create(:name => 'Hamilton', :team_id => 7714, :ranking => 23)
Stanford = Team.create(:name => 'Stanford', :team_id => 7705, :ranking => 24)
Colby = Team.create(:name => 'Colby', :team_id => 7688, :ranking => 25)
Bucknell = Team.create(:name => 'Bucknell', :team_id => 7740, :ranking => 26)
Georgetown = Team.create(:name => 'Georgetown', :team_id => 7719, :ranking => 27)
Hobart = Team.create(:name => 'Hobart', :team_id => 7708, :ranking => 28)
Tufts = Team.create(:name => 'Tufts', :team_id => 7726, :ranking => 29)
JHU = Team.create(:name => 'JHU', :team_id => 7743, :ranking => 30)
Haverford = Team.create(:name => 'Haverford', :team_id => 7715, :ranking => 31)
BC = Team.create(:name => 'BC', :team_id => 7692, :ranking => 32)
BU = Team.create(:name => 'BU', :team_id => 7734, :ranking => 33)
Denison = Team.create(:name => 'Denison', :team_id => 7707, :ranking => 34)
UVA = Team.create(:name => 'UVA', :team_id => 7723, :ranking => 35)
WashU = Team.create(:name => 'WashU', :team_id => 7750, :ranking => 36)
MIT = Team.create(:name => 'MIT', :team_id => 7706, :ranking => 37)
Colgate = Team.create(:name => 'Colgate', :team_id => 7709, :ranking => 38)
